import { defineConfig, devices } from '@playwright/test'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * End-to-end runs drive the appliance the way it actually ships: the backend serves the built
 * frontend out of `frontend/dist`, so the web server below builds and then launches the app
 * with the backend's own virtualenv (the system interpreter has none of the backend's deps).
 *
 * These specs create an administrator and write metadata, so every run gets a throwaway
 * appliance state directory instead of the developer's `backend/data`. Isolation uses the one
 * supported knob, `SPF5000_CONFIG`, pointing at a generated `spf5000.toml` in a fresh temp dir.
 * An already-running server is deliberately *not* reused: that process would carry the real
 * library and state, and these specs mutate it.
 */

// The package is ESM, so there is no __dirname here.
const frontendDir = fileURLToPath(new URL('.', import.meta.url))
const backendDir = resolve(frontendDir, '..', 'backend')
const isWindows = process.platform === 'win32'
const backendPython = join(
  backendDir,
  '.venv',
  isWindows ? 'Scripts' : 'bin',
  isWindows ? 'python.exe' : 'python',
)

const runDir = mkdtempSync(join(tmpdir(), 'spf5000-e2e-'))
const configPath = join(runDir, 'spf5000.toml')
writeFileSync(
  configPath,
  [
    '# Generated by frontend/playwright.config.ts for one end-to-end run. Safe to delete.',
    '[server]',
    'host = "127.0.0.1"',
    'port = 8000',
    '',
    '[paths]',
    `data_dir = "${join(runDir, 'data')}"`,
    `cache_dir = "${join(runDir, 'cache')}"`,
    `log_dir = "${join(runDir, 'logs')}"`,
    '',
    '[logging]',
    'level = "WARNING"',
    '',
  ].join('\n'),
)

export default defineConfig({
  testDir: './e2e',
  // One shared appliance process: setup runs first and later specs observe its effects.
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: process.env.CI
    ? [['github'], ['html', { open: 'never' }]]
    : [['list'], ['html', { open: 'never' }]],
  use: {
    baseURL: 'http://127.0.0.1:8000',
    trace: 'on-first-retry',
  },
  projects: [
    // Creates the administrator the auth specs sign in with, against the same process.
    { name: 'appliance-setup', testMatch: /setup-flow\.spec\.ts/ },
    {
      name: 'chromium',
      dependencies: ['appliance-setup'],
      testIgnore: /setup-flow\.spec\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },
    // Add `firefox` / webkit projects here once `npm run playwright:install` provides them;
    // the kiosk itself is Chromium, so that is the browser worth keeping green by default.
  ],
  webServer: {
    // The app package lives in backend/, so the interpreter has to run from there.
    command: `npm run build && cd "${backendDir}" && "${backendPython}" -m app`,
    cwd: frontendDir,
    env: {
      ...process.env,
      SPF5000_CONFIG: configPath,
      // The specs exercise application behaviour; the rate-limit backstop would only turn a
      // few extra failed-login attempts in this same process into an unrelated 429.
      SPF5000_RATE_LIMIT: 'false',
    },
    url: 'http://127.0.0.1:8000/api/health',
    reuseExistingServer: false,
    timeout: 120_000,
  },
})
