from __future__ import annotations

from typing import Protocol, Any


class PhotoProvider(Protocol):
    def provider_name(self) -> str: ...
    def health_check(self) -> dict[str, Any]: ...
    def list_collections(self) -> list[dict[str, Any]]: ...
    def sync_collection(self, collection_id: str) -> dict[str, Any]: ...
